# Generated by Django 5.2.2 on 2025-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('title', models.TextField(verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('createdDateTime', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': ['Carrer'],
                'ordering': ['username'],
            },
        ),
    ]
