# Generated by Django 5.2.2 on 2025-06-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_careers_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='createdDateTime',
            new_name='created_dateTime',
        ),
    ]
