# Generated by Django 5.2.2 on 2025-06-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_dateTime'], 'verbose_name': ['Comment']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Career',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_dateTime',
        ),
    ]
